<a href="https://colab.research.google.com/github/kookeej/DILAB/blob/main/7.1-7.7/lab01-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

lab01-1
===

# 0. Vector, Matrix, Tensor
* scalar: 차원 없음
* vector: 1차원
* matrix: 2차원
* tensor: 3차원

## 0.1. Pytorch Tensor Shape Convention
* ```tensor```나 ```matrix```를 다룰 때, 언제나 크기가 매우 중요하다. 크기에 대한 이해가 제대로 되어있어야 제대로된 구현이 가능하다.
* 2D Tensor (Typical Simple Setting)
```
|t| = (batch size, dim)    // batch size*dim
```

* 3D Tensor
```
// typical computer vision
|t| = (batch size, width, height)
// typical NLP
|t| = (batch size, length, dim)
```
* rank
```
행공간과 열공간의 차원
ex) A = [[1, -1], [0, 1], [3, -3]]
rank = 2
```

* ndim
```
배열의 차원 수, 또는 배열의 축 수
주로 괄호의 개수를 세면 된다.
```

* shape
```
배열 각 차원의 크기를 튜플 형태로 표현
n행 m열 => (n, m)
```

* dtype
```
배열 원소의 데이터형
```

# 1. Numpy Review

* ```numpy```와 ```pytorch```를 사용하기에 앞서 해당 라이브러리를 먼저 import해준다.

In [1]:
import numpy as np
import torch

* ```numpy```를 사용하면 배열을 아주 간단하게 다룰 수 있다.

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


* t = [0., 1., 2., 3., 4., 5., 6.]의 배열의 축 수, 각 차원의 크기를 출력해본다. 배열의 축 수(차원의 수)는 ```ndim```을, 각 차원의 크기는 ```shape```을 사용한다.

* 배열 t는 1차원이고 행과 열의 개념이 존재하지 않기 때문에 배열 t의 shape은 원소의 개수 7이다.

In [3]:
print('Rank of t :', t.ndim)
print('Shape of t:', t.shape)
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

Rank of t : 1
Shape of t: (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


* 행렬 t는 아래와 같다.
```
t = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]]
```
차원의 수는 괄호의 개수를 세면 된다. 괄호의 개수는 2개이므로 rank=2, shape은 (row num, col num)이므로 (4, 3)이다.

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t: 2
Shape of t: (4, 3)


# 2. Pytorch Tensor

```numpy```가 아니라 ```python```을 사용하여 tensor를 나타낼 수 있다.

In [5]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


* ```dim()```은 차원의 수이므로 1이다. ```shape```과 ```size()```는 둘 다 shape를 나타낸다.

In [6]:
print(t.dim())
print(t.shape)      #shape
print(t.size())     #shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


* 아래는 2차원 배열이다. 차원의 수는 2, shape는 (4, 3)이다.

In [7]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


* t[:, 1]은 모든 행과 index 1의 열을 나타낸다. 따라서,
```
t[:, 1] = [2, 5, 8, 11]
```

* t[:, :-1]는 모든 행과 열의 마지막 인덱스 전까지의 원소를 나타낸다.
```
t[:, :-1] = [[1, 2],
            [4, 5],
            [7, 8],
            [10,11]]
```

In [8]:
print(t.dim()) #rank
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])
print(t[:, :-1].size())
print(t.shape)

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
torch.Size([4, 2])
torch.Size([4, 3])


# 3. Broadcasting

* ```broadcasting```은 자동적으로 크기를 맞추어 연산을 진행시킨다. 

* 아래 코드는 두 행렬의 차원의 크기가 모두 같다. 따라서 그냥 바로 연산을 해주면 된다.

In [9]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


* 아래 코드는 두 행렬의 차원은 같지만 차원의 크기가 다르다. 이때 ```broadcasting```이 일어나서 자동적으로 크기를 맞춰서 계산을 진행시킨다.

In [10]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])                # |m1| = (1, 2)
m2 = torch.FloatTensor([3]) # -> [[3, 3]]       # |m2| = (1,) -> (1, 2)
print(m1 + m2)

tensor([[4., 5.]])


In [11]:
# 2 * 1 vector + 1 * 2 vector
m1 = torch.FloatTensor([[1, 2]])            #|m1| = (1, 2) -> (2, 2)    [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]])          #|m2| = (2, 1) -> (2, 2)    [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


단, broadcasting의 경우 자동으로 실행되기 때문에 사용자 입장에서 주의해서 사용해야 한다.

# 4. Multiplication vs Matrix Multiplication

* ```mul```과 ```matmul``` 비교 연산해보면 아래와 같다.

In [12]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix 2:', m2.shape)
print(m1.matmul(m2))

# Broadcasting이 된다.
print('Shape of Matrix 1:', m1.shape)       # [[1, 2], [3, 4]]
print('Shape of Matrix 2:', m2.shape)       # [[1, 1], [2, 2]]
print(m1 * m2)
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# 5. Other Operation

```mean```, ```sum```, 그리고 ```max```에 관한 연산이다.

## 5.1. Mean

In [13]:
# 행렬의 평균
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [14]:
# 하지만 LongTensor에 대해서는 연산을 수행할 수 없다.
# LongTensor는 64-bit의 부호있는 정수다.

t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [15]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [16]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


* ```t.mean()```일 경우, 모든 원소의 평균을 구한다. 
* ```t.mean(dim=0)```은 axis=0을 기준으로 평균을 구한다. axis=0은 열을 기준으로 한다.
* ```t.mean(dim=1)```은 axis=1을 기준으로 평균을 구한다. axis=1은 행을 기준으로 한다.
* ```t.mean(dim=-1)```은 마지막 차원이다. 여기 2차원 배열에서는 행을 기준으로 한다.

## 5.2. Sum

In [17]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [18]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## 5.3. Max and Argmax
* ```max```는 최댓값, ```Argmax```는 그 index값을 반환해준다.

In [19]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
print(t.max())

tensor(4.)


In [21]:
print(t.max(dim=0))
print('Max:', t.max(dim=0))
print('Argmax:', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max: torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Argmax: tensor([1, 1])


In [22]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
