<a href="https://colab.research.google.com/github/kookeej/DILAB/blob/main/7.1-7.7/lab01-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

# 1. View
```view```는 ```numpy```에서 ```reshape```과 같은 역할을 한다.

In [2]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [3]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [4]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


* ```-1```은 주로 변동이 심한 batch size 등에 사용될 수 있다.
* 이렇게 우리는 ```view```를 사용해서 원하는 형태로 Tensor를 바꿀 수 있다.

# 2. Squeeze
```squeeze```는 차원 중 크기가 1인 것을 찾아 그 차원을 제거하는 함수이다. 예를 들면, |ft| = (3, 1)일 때, 두 번째 원소가 1이므로 1을 버린다. 그러면 |ft| = (3,)이 된다.

In [5]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


* 이처럼 처음 ft의 차원이 (3, 1)이었는데 ```squeeze```를 통해 (3,)이 된다.

In [7]:
print("\n===squeeze 사용 전===")
fft = torch.FloatTensor([[0], [1], [2], [3]])
print(fft)
print(fft.shape)
print("\n===squeeze 사용 후===")
print(fft.squeeze())
print(fft.squeeze().shape)


===squeeze 사용 전===
tensor([[0.],
        [1.],
        [2.],
        [3.]])
torch.Size([4, 1])

===squeeze 사용 후===
tensor([0., 1., 2., 3.])
torch.Size([4])


* 만약 squeeze를 사용할 때 ```dim```을 주게 되면, 해당 차원의 크기가 1이면 squeeze를 사용하고 그렇지 않으면 아무런 변화가 없다.

# 3. Unsqueeze
```unsqueeze```는 squeeze를 반대로 해준다. dim을 명시하고 해당 차원에 1을 넣는다.

In [8]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [9]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


* ```view```를 이용해서 똑같이 구현할 수 있다.

In [10]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# 4. Type Casting
Tensor의 type을 바꿔준다.

In [13]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [14]:
# tensor를 float형으로 바꿔준다.
print(lt.float())

tensor([1., 2., 3., 4.])


In [15]:
bt = torch.ByteTensor([True, True, False, True])
print(bt)

tensor([1, 1, 0, 1], dtype=torch.uint8)


In [16]:
print(bt.long())
print(bt.float())

tensor([1, 1, 0, 1])
tensor([1., 1., 0., 1.])


# 5. Concatenate
```cat```은 tensor를 이어 붙여준다.

In [17]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


* ```dim=0```일 때는 axis=0을 기준으로 concat한다. 행 기준이기 때문에 행의 크기가 증가한다. 따라서 shape는 (4, 2)가 된다.
* ```dim=1```일 때는 axis=1을 기준으로 concat한다. 열 기준이기 때문에 열의 크기가 증가한다. 따라서 shape는 (2, 4)가 된다.

# 6. Stacking
```stack```은 ```concatenate```을 좀 더 편리하게 하는 방법이다.

* ```stack```은 tensor들을 쌓는 것이다. 아래 tensor x, y, z는 모두 shape이 2이다. 

In [18]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))           # (3, 2)로 쌓는다.
print(torch.stack([x, y, z], dim=1))    # dim=1을 기준으로 쌓는다. 열 기준으로 쌓기 때문에 (2, 3)이 된다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


* 위 코드는 아래 코드와 같다.

In [19]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# 7. Ones and Zeros


In [20]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [21]:
print(torch.ones_like(x))       # 1로만 구성된 같은 size의 tensor
print(torch.zeros_like(x))      # 0으로만 구성된 같은 size의 tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 8. In-Place Operation
```_```가 붙게 된다. 메모리를 새로 선언하지 않고 기존의 값에 넣으라는 의미이다.

In [22]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [23]:
print(x.mul(2.))
print(x)            # 원래 x는 변화 없다.
print(x.mul_(2.))
print(x)            # 원래 x까지 변화

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


* 위 코드를 보면 그냥 ```x.mul()```을 했을 경우에는 원래 x는 변화가 없다. ```x.mul_()```은 원래 x까지 변화시킨다.
* ```in-place operation```이 연산 수행이 조금 더 빠르다고 기대할 수 있다.
* 하지만 python의 가비지 컬렉션의 수행이 매우 좋기 때문에 속도 면에서 별다르게 이점은 없을 수 있다.